version: '3.3'

services:
  db: # MySQL Container
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  wordpress: # WordPress Container
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    env_file:
      - ./config/wp.env

volumes:
  db_data: {}